/* Generated by scripts/generate-brand.mjs — do not edit by hand. */
import type { CSSProperties } from "react";

/**
 * The looping Dispatch mark, for rendering inside the app.
 *
 * Styled ENTIRELY by the `.boot-splash__*` rules in index.html's <head> —
 * there is no CSS for this in the bundle, and there must not be, because the
 * splash and this have to be the same animation running off the same clock.
 * Use `<BootMark />` rather than this: it also takes a hold on the colour
 * rotation, without which the mark is whatever hue the splash left behind.
 */
export function BootMarkArt(props: { className?: string; style?: CSSProperties }) {
  return (
    <svg
      className={props.className ? `boot-splash__mark ${props.className}` : "boot-splash__mark"}
      style={props.style}
      viewBox="0 0 64 64"
      aria-hidden="true"
    >
      <g className="boot-splash__collapse">
        <g className="boot-splash__pan">
          <path className="boot-splash__road boot-splash__road--1a" d="M12 32L36 32" pathLength="1" />
          <path className="boot-splash__road boot-splash__road--1b" d="M36 32C42 32 43 22 52 20" pathLength="1" />
          <path className="boot-splash__road boot-splash__road--1b" d="M36 32C42 32 43 42 52 44" pathLength="1" />
          <path className="boot-splash__road boot-splash__road--2b" d="M68 32L92 32" pathLength="1" />
          <path className="boot-splash__road boot-splash__road--2a" d="M52 20C61 22 62 32 68 32" pathLength="1" />
          <path className="boot-splash__road boot-splash__road--2a" d="M52 44C61 42 62 32 68 32" pathLength="1" />
          <circle className="boot-splash__dot boot-splash__dot--a" cx="12" cy="32" r="3.5" />
          <circle className="boot-splash__dot boot-splash__dot--b" cx="52" cy="20" r="3.5" />
          <circle className="boot-splash__dot boot-splash__dot--b" cx="52" cy="44" r="3.5" />
          <circle className="boot-splash__dot boot-splash__dot--c" cx="92" cy="32" r="3.5" />
        </g>
      </g>
    </svg>
  );
}
