/**
 * Runtime configuration, loaded from environment with sensible local defaults.
 * No secrets: auth is the Claude subscription (~/.claude/.credentials.json),
 * never an API key.
 */
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync } from "node:fs";

export interface ServerConfig {
  /** HTTP + WebSocket port. */
  port: number;
  /**
   * Bind host. Defaults to every interface ("host mode") so the app is reachable
   * from other devices on your LAN, not just this machine — see DEFAULT_HOST.
   */
  host: string;
  /**
   * Absolute path to the STATE dir — chats, checkpoints, runners (JSON + JSONL,
   * no DB). Per-instance: two processes must never share this (see Store).
   */
  dataDir: string;
  /**
   * Absolute path to the CONFIG dir — settings, projects, agents, modes. Safe to
   * point two instances (stable + dev) at one shared location.
   *
   * UNDEFINED unless `DISPATCH_CONFIG_DIR` is set, and deliberately so: the Store then
   * falls back to `dataDir` (the original single-root layout). Leaving it unset
   * rather than eagerly resolving it is what keeps `{ ...loadConfig(), dataDir:
   * tmp }` — the shape every test uses — from silently pointing config reads at
   * the developer's REAL `.data` while state goes to a temp dir.
   */
  configDir?: string;
  /** Max concurrently-active SDK sessions (idle chats don't count). */
  maxActiveSessions: number;
}

const DEFAULT_PORT = 4319;
/**
 * Every interface, not loopback — "host mode" is the default launch.
 *
 * The point is reaching the same control plane from a phone or a laptop on the
 * same network while agents keep running on this box. Loopback made that
 * impossible without an env var nobody remembers to set.
 *
 * Two things to know before you leave it on:
 *
 *  1. **There is no auth.** Anything that can reach this port can start a chat,
 *     approve a tool call, and therefore run commands as you. That's fine on a
 *     home LAN behind NAT and NOT fine on a network you don't control — set
 *     `DISPATCH_HOST=127.0.0.1` there, which still works and takes precedence.
 *  2. **A LAN origin is not a secure context.** `http://<lan-ip>:4318` gets no
 *     service worker, no install prompt and no Notification API from Chromium —
 *     only `http://localhost` and HTTPS do. The client degrades honestly (see
 *     `lib/browserNotify.ts`) rather than showing dead buttons.
 */
const DEFAULT_HOST = "0.0.0.0";
/**
 * The app root = nearest ancestor of this module containing `pnpm-workspace.yaml`.
 * Keeps `.data` co-located with the app so the whole folder stays portable — moving
 * or renaming the app dir just works (no baked-in absolute path).
 * `DISPATCH_DATA_DIR` still overrides.
 */
function findAppRoot(): string {
  const start = dirname(fileURLToPath(import.meta.url));
  let dir = start;
  for (let i = 0; i < 8; i++) {
    if (existsSync(resolve(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // Fallback: built layout is <root>/packages/server/dist/<file>.js → up three.
  return resolve(start, "../../..");
}

const DEFAULT_DATA_DIR = resolve(findAppRoot(), ".data");
const DEFAULT_MAX_ACTIVE = 6;

/**
 * Read `DISPATCH_<suffix>`, falling back to the pre-rename `CM_<suffix>`.
 *
 * The old names stay honoured because they escape this repo: they live in shell
 * profiles and in whatever start-menu shortcut is currently on disk, which may
 * predate the rename. Nothing in-tree sets `CM_*` any more — drop the fallback
 * once every shortcut has been regenerated by `pnpm app:shortcut`.
 */
export function envVar(env: NodeJS.ProcessEnv, suffix: string): string | undefined {
  return env[`DISPATCH_${suffix}`] ?? env[`CM_${suffix}`];
}

function intFromEnv(env: NodeJS.ProcessEnv, suffix: string, fallback: number): number {
  const raw = envVar(env, suffix);
  if (raw === undefined || raw.trim() === "") return fallback;
  const n = Number.parseInt(raw, 10);
  return Number.isFinite(n) ? n : fallback;
}

/** Build the effective config from process.env (call once at boot). */
export function loadConfig(env: NodeJS.ProcessEnv = process.env): ServerConfig {
  const rawDataDir = envVar(env, "DATA_DIR");
  const dataDir = rawDataDir ? resolve(rawDataDir) : DEFAULT_DATA_DIR;
  // Left undefined when unset => single-root layout, byte-identical to the
  // pre-split behaviour. Only the desktop/stable deployment sets it.
  const rawConfigDir = envVar(env, "CONFIG_DIR");
  const configDir = rawConfigDir ? resolve(rawConfigDir) : undefined;
  return {
    port: intFromEnv(env, "PORT", DEFAULT_PORT),
    host: envVar(env, "HOST")?.trim() || DEFAULT_HOST,
    dataDir,
    ...(configDir ? { configDir } : {}),
    maxActiveSessions: intFromEnv(env, "MAX_ACTIVE_SESSIONS", DEFAULT_MAX_ACTIVE),
  };
}

export const config: ServerConfig = loadConfig();
