/**
 * Runtime configuration, loaded from environment with sensible local defaults.
 * No secrets: auth is the Claude subscription (~/.claude/.credentials.json),
 * never an API key.
 */
import { DEFAULT_MAX_ACTIVE_SESSIONS } from "@dispatch/shared";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { existsSync } from "node:fs";

export interface ServerConfig {
  /** HTTP + WebSocket port. */
  port: number;
  /** Bind host. Defaults to loopback; host mode must be explicitly enabled. */
  host: string;
  /**
   * Absolute path to the STATE dir — chats, checkpoints, runners (JSON + JSONL,
   * no DB). Per-instance: two processes must never share this (see Store).
   */
  dataDir: string;
  /**
   * Absolute path to the CONFIG dir — settings, projects, agents, modes. Safe to
   * point two instances (stable + dev) at one shared location.
   *
   * UNDEFINED unless `DISPATCH_CONFIG_DIR` is set, and deliberately so: the Store then
   * falls back to `dataDir` (the original single-root layout). Leaving it unset
   * rather than eagerly resolving it is what keeps `{ ...loadConfig(), dataDir:
   * tmp }` — the shape every test uses — from silently pointing config reads at
   * the developer's REAL `.data` while state goes to a temp dir.
   */
  configDir?: string;
  /**
   * Max concurrently-active SDK sessions (idle chats don't count) — the DEFAULT
   * only. `AppSettings.maxActiveSessions` overrides it at runtime and does not
   * need a restart; this is what a cleared setting falls back to.
   */
  maxActiveSessions: number;
}

const DEFAULT_PORT = 4319;
/**
 * Loopback is the secure default. Host mode is useful for reaching the same
 * control plane from another device while agents keep running on this box, but
 * it must be an explicit choice because:
 *
 *  1. **Auth defaults off.** Until the owner enables it in Settings, anything
 *     that can reach this port can start a chat and run commands as you. Set a
 *     wildcard host only on a trusted network or after configuring auth.
 *  2. **A LAN origin is not a secure context.** `http://<lan-ip>:4318` gets no
 *     service worker, no install prompt and no Notification API from Chromium —
 *     only `http://localhost` and HTTPS do. The client degrades honestly (see
 *     `lib/browserNotify.ts`) rather than showing dead buttons.
 */
const DEFAULT_HOST = "127.0.0.1";
/**
 * The app root = nearest ancestor of this module containing `pnpm-workspace.yaml`.
 * Keeps `.data` co-located with the app so the whole folder stays portable — moving
 * or renaming the app dir just works (no baked-in absolute path).
 * `DISPATCH_DATA_DIR` still overrides.
 */
function findAppRoot(): string {
  const start = dirname(fileURLToPath(import.meta.url));
  let dir = start;
  for (let i = 0; i < 8; i++) {
    if (existsSync(resolve(dir, "pnpm-workspace.yaml"))) return dir;
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // Fallback: built layout is <root>/packages/server/dist/<file>.js → up three.
  return resolve(start, "../../..");
}

const DEFAULT_DATA_DIR = resolve(findAppRoot(), ".data");

/**
 * Every prefix a manager-owned variable is recognised under, most-preferred
 * first: `DISPATCH_`, then the pre-rename `CM_`.
 *
 * The old names stay honoured because they escape this repo: they live in shell
 * profiles and in whatever start-menu shortcut is currently on disk, which may
 * predate the rename. Nothing in-tree sets `CM_*` any more — drop the fallback
 * once every shortcut has been regenerated by `pnpm app:shortcut`.
 *
 * Exported because reading these names is not the only thing anyone does with
 * them: the subApp runner has to REMOVE them from a child's environment
 * (`MANAGER_ENV_VARS` in `services/runner.ts`). A scrub list that hard-coded
 * only `DISPATCH_*` would leave the `CM_*` spelling — which `envVar` still
 * falls back to — reading straight through, so both sides derive their names
 * from this one list and cannot drift apart.
 */
export const ENV_PREFIXES = ["DISPATCH_", "CM_"] as const;

/** Every name `envVar` would accept for `suffix`, most-preferred first. */
export function envNames(suffix: string): string[] {
  return ENV_PREFIXES.map((prefix) => `${prefix}${suffix}`);
}

/** Read `DISPATCH_<suffix>`, falling back to the pre-rename `CM_<suffix>`. */
export function envVar(env: NodeJS.ProcessEnv, suffix: string): string | undefined {
  for (const name of envNames(suffix)) {
    const value = env[name];
    if (value !== undefined) return value;
  }
  return undefined;
}

function intFromEnv(env: NodeJS.ProcessEnv, suffix: string, fallback: number): number {
  const raw = envVar(env, suffix);
  if (raw === undefined || raw.trim() === "") return fallback;
  const n = Number.parseInt(raw, 10);
  return Number.isFinite(n) ? n : fallback;
}

/** Build the effective config from process.env (call once at boot). */
export function loadConfig(env: NodeJS.ProcessEnv = process.env): ServerConfig {
  const rawDataDir = envVar(env, "DATA_DIR");
  const dataDir = rawDataDir ? resolve(rawDataDir) : DEFAULT_DATA_DIR;
  // Left undefined when unset => single-root layout, byte-identical to the
  // pre-split behaviour. Only the desktop/stable deployment sets it.
  const rawConfigDir = envVar(env, "CONFIG_DIR");
  const configDir = rawConfigDir ? resolve(rawConfigDir) : undefined;
  return {
    port: intFromEnv(env, "PORT", DEFAULT_PORT),
    host: envVar(env, "HOST")?.trim() || DEFAULT_HOST,
    dataDir,
    ...(configDir ? { configDir } : {}),
    // Clamped here, not just in the broker: `intFromEnv` accepts any parseable
    // integer, so `DISPATCH_MAX_ACTIVE_SESSIONS=0` — the obvious typo for someone
    // reaching for "unlimited" — used to put a cap in `ServerConfig` that the
    // broker would never honour, and `/api/settings/defaults` would then report
    // it to the settings field as though it were in force.
    maxActiveSessions: Math.max(
      1,
      intFromEnv(env, "MAX_ACTIVE_SESSIONS", DEFAULT_MAX_ACTIVE_SESSIONS),
    ),
  };
}

export const config: ServerConfig = loadConfig();
